// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dejyjyilonbykdpskbww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlanlqeWlsb25ieWtkcHNrYnd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODYwMDksImV4cCI6MjA3NDg2MjAwOX0.iP-YYXsDBHkZ7EQqn3wEUt_95V16huxiR-CR1iSwO2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});